// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: updated_member.proto

package events

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	members "github.com/UptownRunners/common/members/v1/go/members"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = members.MemberShipType(0)

	_ = members.MembershipStatus(0)
)

// Validate checks the field values on UpdatedMemberEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdatedMemberEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdatedMemberEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdatedMemberEventMultiError, or nil if none found.
func (m *UpdatedMemberEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdatedMemberEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MemberId

	// no validation rules for UserId

	// no validation rules for FirstName

	// no validation rules for LastName

	// no validation rules for Address

	// no validation rules for PhoneNumber

	// no validation rules for NationalIdentifier

	// no validation rules for Email

	if all {
		switch v := interface{}(m.GetRenewedDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdatedMemberEventValidationError{
					field:  "RenewedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdatedMemberEventValidationError{
					field:  "RenewedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRenewedDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdatedMemberEventValidationError{
				field:  "RenewedDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOverrideExpirationDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdatedMemberEventValidationError{
					field:  "OverrideExpirationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdatedMemberEventValidationError{
					field:  "OverrideExpirationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOverrideExpirationDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdatedMemberEventValidationError{
				field:  "OverrideExpirationDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for MembershipType

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdatedMemberEventMultiError(errors)
	}
	return nil
}

// UpdatedMemberEventMultiError is an error wrapping multiple validation errors
// returned by UpdatedMemberEvent.ValidateAll() if the designated constraints
// aren't met.
type UpdatedMemberEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdatedMemberEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdatedMemberEventMultiError) AllErrors() []error { return m }

// UpdatedMemberEventValidationError is the validation error returned by
// UpdatedMemberEvent.Validate if the designated constraints aren't met.
type UpdatedMemberEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatedMemberEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatedMemberEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatedMemberEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatedMemberEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatedMemberEventValidationError) ErrorName() string {
	return "UpdatedMemberEventValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatedMemberEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatedMemberEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatedMemberEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatedMemberEventValidationError{}
