// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: v2/updated_member_event.proto

package events

import (
	members "github.com/UptownRunners/common/go/members/v2/members"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMemberEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Before *members.Member `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After  *members.Member `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
}

func (x *UpdateMemberEvent) Reset() {
	*x = UpdateMemberEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v2_updated_member_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMemberEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberEvent) ProtoMessage() {}

func (x *UpdateMemberEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v2_updated_member_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberEvent.ProtoReflect.Descriptor instead.
func (*UpdateMemberEvent) Descriptor() ([]byte, []int) {
	return file_v2_updated_member_event_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMemberEvent) GetBefore() *members.Member {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *UpdateMemberEvent) GetAfter() *members.Member {
	if x != nil {
		return x.After
	}
	return nil
}

var File_v2_updated_member_event_proto protoreflect.FileDescriptor

var file_v2_updated_member_event_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x76, 0x32, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x18, 0x75, 0x70, 0x74, 0x6f, 0x77, 0x6e, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x32, 0x1a, 0x10, 0x76, 0x32, 0x2f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x39, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x75, 0x70, 0x74, 0x6f, 0x77, 0x6e, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x37, 0x0a, 0x05,
	0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x75, 0x70,
	0x74, 0x6f, 0x77, 0x6e, 0x5f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x05,
	0x61, 0x66, 0x74, 0x65, 0x72, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x55, 0x70, 0x74, 0x6f, 0x77, 0x6e, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v2_updated_member_event_proto_rawDescOnce sync.Once
	file_v2_updated_member_event_proto_rawDescData = file_v2_updated_member_event_proto_rawDesc
)

func file_v2_updated_member_event_proto_rawDescGZIP() []byte {
	file_v2_updated_member_event_proto_rawDescOnce.Do(func() {
		file_v2_updated_member_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_updated_member_event_proto_rawDescData)
	})
	return file_v2_updated_member_event_proto_rawDescData
}

var file_v2_updated_member_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v2_updated_member_event_proto_goTypes = []interface{}{
	(*UpdateMemberEvent)(nil), // 0: uptown_runners.events.v2.UpdateMemberEvent
	(*members.Member)(nil),    // 1: uptown_runners.members.v2.Member
}
var file_v2_updated_member_event_proto_depIdxs = []int32{
	1, // 0: uptown_runners.events.v2.UpdateMemberEvent.before:type_name -> uptown_runners.members.v2.Member
	1, // 1: uptown_runners.events.v2.UpdateMemberEvent.after:type_name -> uptown_runners.members.v2.Member
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v2_updated_member_event_proto_init() }
func file_v2_updated_member_event_proto_init() {
	if File_v2_updated_member_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v2_updated_member_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMemberEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_updated_member_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_updated_member_event_proto_goTypes,
		DependencyIndexes: file_v2_updated_member_event_proto_depIdxs,
		MessageInfos:      file_v2_updated_member_event_proto_msgTypes,
	}.Build()
	File_v2_updated_member_event_proto = out.File
	file_v2_updated_member_event_proto_rawDesc = nil
	file_v2_updated_member_event_proto_goTypes = nil
	file_v2_updated_member_event_proto_depIdxs = nil
}
